#define TILE1_BOTTOM "../assets/tiles/tile1Bottom.png"
#define TILE1_BOTTOM_CORNER_LEFT "../assets/tiles/tile1BottomCornerLeft.png"
#define TILE1_BOTTOM_CORNER_RIGHT "../assets/tiles/tile1BottomCornerRight.png"
#define TILE1_TOP "../assets/tiles/tile1Top.png"
#define TILE1_TOP_CORNER_LEFT "../assets/tiles/tile1TopCornerLeft.png"
#define TILE1_TOP_CORNER_RIGHT "../assets/tiles/tile1TopCornerLeft.png"
#define TILE1_WALL_LEFT "../assets/tiles/tile1WallLeft.png"
#define TILE1_WALL_RIGHT "../assets/tiles/tile1WallRight.png"
#define TILE1_BACKGROUND "../assets/tiles/tile1background.png"

#define TILE2_BOTTOM "../assets/tiles/tile2Bottom.png"
#define TILE2_BOTTOM_CORNER_LEFT "../assets/tiles/tile2BottomCornerLeft.png"
#define TILE2_BOTTOM_CORNER_RIGHT "../assets/tiles/tile2BottomCornerRight.png"
#define TILE2_TOP "../assets/tiles/tile2Top.png"
#define TILE2_TOP_CORNER_LEFT "../assets/tiles/tile2TopCornerLeft.png"
#define TILE2_TOP_CORNER_RIGHT "../assets/tiles/tile2TopCornerLeft.png"
#define TILE2_WALL_LEFT "../assets/tiles/tile2WallLeft.png"
#define TILE2_WALL_RIGHT "../assets/tiles/tile2WallRight.png"
#define TILE2_BACKGROUND "../assets/tiles/tile2background.png"

