#define PLAYER1_TEXTURE_PATH "../assets/biker.png"
#define PLAYER2_TEXTURE_PATH "../assets/cyborg.png"
#define ENEMY_TEXTURE_PATH "../assets/smoker.png"
#define TILE_TEXTURE_PATH "../assets/tile1.png"
#define BACKGROUND1_TEXTURE_PATH "../assets/background.png"
#define BACKGROUND2_TEXTURE_PATH "../assets/background.png"